#Physical Attributes
int32 locomotion
float32 width
float32 length
float32 expendability
bool debris_remover
int32 marker_count

#Computational Attributes
bool victim_tracker
bool frontier_finder
bool maintain_team_map
bool assign_tasks
bool planner

#Sensory Attributes
int32 victim_sensor
bool robot_sensor
int32 sonar_sensors
float32 sonar_range
bool laser_rangefinder
bool victim_marker_detector
